const fs = require("fs");
const path = require("path");
const { run } = require("../utils.cjs");
const { loadFiles, EXTENSIONS_BY_STACK, loadOverrides } = require("./scan-utils.cjs");
const { scan: namingScan } = require("./scanners/naming.cjs");
const { scan: structureScan } = require("./scanners/structure.cjs");
const { scan: patternsScan } = require("./scanners/patterns.cjs");
const { scan: importsScan } = require("./scanners/imports.cjs");

function getExtensions(cwd) {
  const profilePath = path.join(cwd, ".opencraft", "profile.json");
  try {
    const profile = JSON.parse(fs.readFileSync(profilePath, "utf-8"));
    const exts = new Set();
    for (const stack of profile.techStack || []) {
      for (const e of EXTENSIONS_BY_STACK[stack] || []) exts.add(e);
    }
    return exts.size > 0 ? [...exts] : [".ts", ".tsx", ".js", ".jsx", ".py"];
  } catch {
    return [".ts", ".tsx", ".js", ".jsx", ".py"];
  }
}

function readComment(content, key) {
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const re = new RegExp(`<!--\\s*${escaped}:\\s*(.+?)\\s*-->`);
  const m = content.match(re);
  return m ? m[1].trim() : null;
}

function getHeadShort(cwd) {
  const r = run("git rev-parse --short HEAD", { cwd, timeout: 3000 });
  return r.ok ? r.stdout.trim() : null;
}

function shouldRescan(cwd) {
  const convPath = path.join(cwd, ".opencraft", "conventions.md");
  if (!fs.existsSync(convPath)) return { needScan: true, reason: "no-cache" };

  const content = fs.readFileSync(convPath, "utf-8");
  const lastCommit = readComment(content, "last-commit");
  const currentCommit = getHeadShort(cwd);

  if (!lastCommit || !currentCommit) return { needScan: true, reason: "no-git" };
  if (lastCommit === currentCommit) return { needScan: false, reason: "same-commit" };

  return { needScan: true, reason: "commit-changed" };
}

function mergeResults(results) {
  const merged = {};
  for (const r of results) {
    for (const [key, value] of Object.entries(r)) {
      merged[key] = value;
    }
  }
  return merged;
}

function applyOverrides(result, overrides) {
  if (!overrides) return result;
  const o = overrides;

  // Exclude scanners
  if (Array.isArray(o.exclude)) {
    for (const scanner of o.exclude) {
      if (result[scanner]) {
        result[scanner] = null;
      }
    }
  }

  // Override conventions — deep merge override values into result
  if (o.conventions && typeof o.conventions === "object") {
    for (const [category, values] of Object.entries(o.conventions)) {
      if (result[category] && typeof values === "object") {
        for (const [key, value] of Object.entries(values)) {
          if (value != null) {
            result[category][key] = value;
          }
        }
      }
    }
  }

  return result;
}

function formatConventionsMd(result, commitHash, date) {
  const lines = [
    "# Project Conventions",
    `<!-- Auto-generated by opencraft. Last scan: ${date} -->`,
    "<!-- DO NOT EDIT — regenerated when code changes detected -->",
    "<!-- Review/adjust: /opencraft:setup or edit overrides.yaml -->",
    `<!-- last-commit: ${commitHash || "unknown"} -->`,
    "",
  ];

  // Naming
  const n = result.naming || {};
  lines.push("## Naming");
  if (n.functions) lines.push(`- **Functions**: ${n.functions}${n.functionPrefixes?.length ? ", prefixes: " + n.functionPrefixes.join(" / ") : ""}`);
  if (n.variables) lines.push(`- **Variables**: ${n.variables}`);
  if (n.constants) lines.push(`- **Constants**: ${n.constants}`);
  if (n.files) lines.push(`- **Files**: ${n.files}`);
  if (n.classes) lines.push(`- **Classes/Components**: ${n.classes}`);
  if (n.testFiles) lines.push(`- **Test files**: *${n.testFiles}*.{ext}`);
  if (n.confidence > 0) lines.push(`- **Confidence**: ${n.confidence}% of codebase matches`);
  lines.push("");

  // Structure
  const s = result.structure || {};
  lines.push("## Structure");
  if (s.avgFnLength > 0) lines.push(`- Avg function length: ${s.avgFnLength} lines (P75 = ${s.p75}, P90 = ${s.p90})`);
  if (s.avgFileLength > 0) lines.push(`- Avg file length: ${s.avgFileLength} lines (max: ${s.maxFileLength})`);
  if (s.testDir) lines.push(`- Test directory: ${s.testDir}/`);
  if (s.srcDir) lines.push(`- Source directory: ${s.srcDir}/`);
  if (s.exportStyle) lines.push(`- Prefer ${s.exportStyle} exports`);
  lines.push("");

  // Patterns
  const p = result.patterns || {};
  lines.push("## Patterns");
  if (p.errorHandling) lines.push(`- Error handling: ${p.errorHandling}`);
  if (p.stateManagement) lines.push(`- State management: ${p.stateManagement}`);
  if (p.apiCalls) lines.push(`- API calls: ${p.apiCalls}`);
  if (p.styling) lines.push(`- Styling: ${p.styling}`);
  if (p.testing) lines.push(`- Testing: ${p.testing}`);
  lines.push("");

  // Imports
  const imp = result.imports || {};
  lines.push("## Imports");
  if (imp.aliases?.length > 0) {
    const aliasStr = imp.aliases.map(a => `${a.alias} → ${a.target}`).join(", ");
    lines.push(`- Path alias: ${aliasStr}`);
  }
  if (imp.style) lines.push(`- Style: ${imp.style} imports preferred`);
  if (imp.barrelExports) lines.push("- Barrel exports: index files re-export");
  lines.push("");

  return lines.join("\n");
}

function saveConventions(cwd, content, result) {
  const dir = path.join(cwd, ".opencraft");
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, "conventions.md"), content, "utf-8");
  fs.writeFileSync(path.join(dir, "conventions.json"), JSON.stringify(result), "utf-8");
}

function loadConventionsMd(cwd) {
  const p = path.join(cwd, ".opencraft", "conventions.md");
  try { return fs.readFileSync(p, "utf-8"); } catch { return null; }
}

function loadConventionsResult(cwd) {
  const p = path.join(cwd, ".opencraft", "conventions.json");
  try { return JSON.parse(fs.readFileSync(p, "utf-8")); } catch { return null; }
}

function runScan(cwd) {
  const { needScan, reason } = shouldRescan(cwd);

  if (!needScan) {
    return { cached: true, reason, conventionsMd: loadConventionsMd(cwd), result: loadConventionsResult(cwd) };
  }

  const extensions = getExtensions(cwd);
  const files = loadFiles(cwd, extensions);

  if (files.length === 0) {
    return { cached: false, reason: "no-files", conventionsMd: null, result: null };
  }

  const scannerResults = [
    namingScan(files),
    structureScan(files),
    patternsScan(files),
    importsScan(files, cwd),
  ];

  const merged = mergeResults(scannerResults);
  const overrides = loadOverrides(cwd);
  applyOverrides(merged, overrides);
  const commit = getHeadShort(cwd);
  const date = new Date().toISOString().split("T")[0];
  const md = formatConventionsMd(merged, commit, date);

  saveConventions(cwd, md, merged);

  return { cached: false, reason, result: merged, conventionsMd: md };
}

function formatContextSummary(result) {
  if (!result) return null;
  const lines = [];

  const n = result.naming;
  if (n) {
    const parts = [];
    if (n.functions) parts.push(`函数 ${n.functions} (${(n.functionPrefixes || []).slice(0, 4).join("/")})`);
    if (n.files) parts.push(`文件 ${n.files}`);
    if (n.constants) parts.push(`常量 ${n.constants}`);
    if (parts.length > 0) lines.push(`命名：${parts.join("，")}`);
  }

  const s = result.structure;
  if (s && s.avgFnLength > 0) {
    const parts = [`函数平均 ${s.avgFnLength} 行`];
    if (s.p75) parts.push(`P75=${s.p75}`);
    if (s.testDir) parts.push(`测试放 ${s.testDir}/`);
    lines.push(`结构：${parts.join("，")}`);
  }

  const p = result.patterns;
  if (p) {
    const parts = [];
    if (p.errorHandling) parts.push(`错误处理 ${p.errorHandling}`);
    if (p.stateManagement) parts.push(`状态管理 ${p.stateManagement}`);
    if (p.testing) parts.push(`测试 ${p.testing}`);
    if (parts.length > 0) lines.push(`模式：${parts.join("，")}`);
  }

  const imp = result.imports;
  if (imp) {
    const parts = [];
    if (imp.aliases?.length > 0) parts.push(`路径别名 ${imp.aliases.map(a => a.alias).join(", ")}`);
    if (imp.style) parts.push(`${imp.style}导入为主`);
    if (imp.barrelExports) parts.push("barrel exports");
    if (parts.length > 0) lines.push(`导入：${parts.join("，")}`);
  }

  return lines.length > 0 ? lines.join("\n") : null;
}

function countConventions(result) {
  if (!result) return 0;
  let count = 0;
  if (result.naming?.functions) count++;
  if (result.naming?.files) count++;
  if (result.naming?.constants) count++;
  if (result.naming?.classes) count++;
  if (result.structure?.avgFnLength > 0) count++;
  if (result.patterns?.errorHandling) count++;
  if (result.patterns?.stateManagement) count++;
  if (result.patterns?.testing) count++;
  if (result.patterns?.styling) count++;
  if (result.imports?.aliases?.length > 0) count++;
  if (result.imports?.style) count++;
  return count;
}

module.exports = {
  runScan, shouldRescan, formatConventionsMd, saveConventions,
  loadConventionsMd, loadConventionsResult, readComment, mergeResults, applyOverrides,
  formatContextSummary, countConventions,
};
