module.exports = [
  {
    id: "gcp-api-key",
    type: "secret",
    name: "GCP API Key",
    severity: "critical",
    keywords: ["AIza"],
    regex: /\b(AIza[\w-]{35})\b/,
    entropy: 4,
    allowlist: [
      /AIzaSyAnLA7NfeLquW1tJFpx_eQCxoX-oo6YyIs/,
      /AIzaSyBzlLYy3sCoCBl-x8h4YjU1S8ZVri-xL8M/,
      /AIzaSyCF5i1l-cBYwk3O6LeaNEDqYJcW8qCgT-0/,
      /AIzaSyD1U-VXMWpwzO-Cz_gxhRIfJjUcMHQDQh4/,
      /AIzaSyDfjAK1GPGSG7-OhYDtVnv0OX6C-mx-gI0/,
      /AIzaSyBG7TKNqi8IqQs8CSMR8vq2gJqvlInQpBk/,
      /AIzaSyCL3s-BJSXGq3lXgl-ASmqwMFMvJMSDNf0/,
      /AIzaSyCk6KLx19MGEFJDOj5kzWi0E_ihWbk-eqc/,
      /AIzaSyA4UvbSMqdv0qM4eLGLFCR0R3S-soYJqa4/,
      /AIzaSyBvdj8I0FRboJPVLXHeOXGN2mGKqKFdajE/,
      /AIzaSyC4Y7bWMwm-4Y7S6MSxJ7xdDz5F4qU-e0s/,
      /AIzaSyA2HtdMhIJCFfGGLMlFakSm7CZKc7PL7pI/,
      /AIzaSyA9YjgT6FLP5bqNMvKFnYj0ErRk-qR7vdA/,
      /AIzaSyA0JMxp6b3NzZq1D4qftLJYAKFnE4yUCUo/,
      /AIzaSyAcE7YGcmghOwSNN1GKagLZTTaFfT1YdpA/,
      /AIzaSyD-uJiGdG1ZmeXJyrSfDoGmcYGQ5P8LfkA/,
    ],
  },
];
