module.exports = [
  {
    id: "github-pat",
    name: "GitHub Personal Access Token",
    type: "secret",
    severity: "critical",
    keywords: ["ghp_"],
    regex: /ghp_[0-9a-zA-Z]{36}/,
    entropy: 3,
    allowlist: [/ghp_[xX]{36}/],
  },
  {
    id: "github-fine-grained-pat",
    name: "GitHub Fine-Grained PAT",
    type: "secret",
    severity: "critical",
    keywords: ["github_pat_"],
    regex: /github_pat_\w{82}/,
    entropy: 3,
    allowlist: [/github_pat_[xX]{82}/],
  },
  {
    id: "github-oauth",
    name: "GitHub OAuth Access Token",
    type: "secret",
    severity: "critical",
    keywords: ["gho_"],
    regex: /gho_[0-9a-zA-Z]{36}/,
    entropy: 3,
    allowlist: [/gho_[xX]{36}/],
  },
  {
    id: "github-app-token",
    name: "GitHub App Token",
    type: "secret",
    severity: "critical",
    keywords: ["ghu_", "ghs_"],
    regex: /(?:ghu|ghs)_[0-9a-zA-Z]{36}/,
    entropy: 3,
    allowlist: [/gh[su]_[xX]{36}/],
  },
  {
    id: "github-refresh-token",
    name: "GitHub Refresh Token",
    type: "secret",
    severity: "high",
    keywords: ["ghr_"],
    regex: /ghr_[0-9a-zA-Z]{36}/,
    entropy: 3,
    allowlist: [/ghr_[xX]{36}/],
  },
];
